---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    cloudsate_protocol_major_version: '0'
    cloudsate_protocol_minor_version: '1'
    eigr_functions_protocol_major_version: '0'
    eigr_functions_protocol_minor_version: '1'
    proxy_name: massa-proxy
    k8s-app: eigr-functions-controller
  name: functions.functions.eigr.io
spec:
  additionalPrinterColumns: []
  group: functions.eigr.io
  names:
    kind: Function
    plural: functions
    shortNames:
      - f
      - fs
      - fc
      - fcs
      - func
      - function
      - funcs
      - functions
    singular: function
  scope: Namespaced
  version: v1

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    cloudsate_protocol_major_version: '0'
    cloudsate_protocol_minor_version: '1'
    eigr_functions_protocol_major_version: '0'
    eigr_functions_protocol_minor_version: '1'
    proxy_name: massa-proxy
    k8s-app: eigr-functions-controller
  name: persistentfunctions.functions.eigr.io
spec:
  additionalPrinterColumns: []
  group: functions.eigr.io
  names:
    kind: PersistentFunction
    plural: persistentfunctions
    shortNames:
      - pf
      - pfs
      - pfc
      - pfcs
      - pfunc
      - pfunction
      - pfuncs
      - pfunctions
      - persistentfunction
      - persistentfunctions
    singular: persistentfunction
  scope: Namespaced
  version: v1

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    cloudsate_protocol_major_version: '0'
    cloudsate_protocol_minor_version: '1'
    eigr_functions_protocol_major_version: '0'
    eigr_functions_protocol_minor_version: '1'
    proxy_name: massa-proxy
    k8s-app: eigr-functions-controller
  name: eigr-functions-controller
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - functions.eigr.io
    resources:
      - functions
    verbs:
      - '*'
  - apiGroups:
      - functions.eigr.io
    resources:
      - persistentfunctions
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - configmaps
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - configmaps
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - statefulsets
      - deployments
    verbs:
      - '*'

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    cloudsate_protocol_major_version: '0'
    cloudsate_protocol_minor_version: '1'
    eigr_functions_protocol_major_version: '0'
    eigr_functions_protocol_minor_version: '1'
    proxy_name: massa-proxy
    k8s-app: eigr-functions-controller
  name: eigr-functions-controller
  namespace: eigr-functions

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    cloudsate_protocol_major_version: '0'
    cloudsate_protocol_minor_version: '1'
    eigr_functions_protocol_major_version: '0'
    eigr_functions_protocol_minor_version: '1'
    proxy_name: massa-proxy
    k8s-app: eigr-functions-controller
  name: eigr-functions-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eigr-functions-controller
subjects:
  - kind: ServiceAccount
    name: eigr-functions-controller
    namespace: eigr-functions
