---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cloudsate_protocol_major_version: '0'
    cloudsate_protocol_minor_version: '1'
    eigr_functions_protocol_major_version: '0'
    eigr_functions_protocol_minor_version: '1'
    proxy_name: massa-proxy
    k8s-app: eigr-functions-controller
  name: eigr-functions-controller
  namespace: eigr-functions
spec:
  replicas: 1
  selector:
    matchLabels:
      cloudsate_protocol_major_version: '0'
      cloudsate_protocol_minor_version: '1'
      eigr_functions_protocol_major_version: '0'
      eigr_functions_protocol_minor_version: '1'
      proxy_name: massa-proxy
      k8s-app: eigr-functions-controller
  template:
    metadata:
      labels:
        cloudsate_protocol_major_version: '0'
        cloudsate_protocol_minor_version: '1'
        eigr_functions_protocol_major_version: '0'
        eigr_functions_protocol_minor_version: '1'
        proxy_name: massa-proxy
        k8s-app: eigr-functions-controller
    spec:
      containers:
        - env:
            - name: MIX_ENV
              value: prod
            - name: BONNY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BONNY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: BONNY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: BONNY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          image: ghcr.io/eigr/functions-controller:0.1.36
          name: eigr-functions-controller
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 200m
              memory: 200Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
      serviceAccountName: eigr-functions-controller

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    cloudsate_protocol_major_version: '0'
    cloudsate_protocol_minor_version: '1'
    eigr_functions_protocol_major_version: '0'
    eigr_functions_protocol_minor_version: '1'
    proxy_name: massa-proxy
    k8s-app: eigr-functions-controller
  name: functions.functions.eigr.io
spec:
  additionalPrinterColumns:
    - JSONPath: .spec.backend.runtime
      description: Runtime for function execution
      name: runtime
      type: string
    - JSONPath: .spec.backend.language
      description: User function language
      name: language
      type: string
    - JSONPath: .spec.backend.expose.method
      description: Method used to expose function
      name: expose method
      type: string
    - JSONPath: .spec.backend.features.httpTranscode
      description: Whether HTTP transcode is enabled
      name: http transcode
      type: boolean
    - JSONPath: .spec.backend.features.eventing
      description: Whether the function is eventing enabled
      name: eventing
      type: boolean
    - JSONPath: .metadata.creationTimestamp
      description: |-
        CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.
        
              Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
      name: Age
      type: date
  group: functions.eigr.io
  names:
    kind: Function
    plural: functions
    shortNames:
      - f
      - fs
      - fc
      - fcs
      - func
      - function
      - funcs
      - functions
    singular: function
  scope: Cluster
  version: v1

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    cloudsate_protocol_major_version: '0'
    cloudsate_protocol_minor_version: '1'
    eigr_functions_protocol_major_version: '0'
    eigr_functions_protocol_minor_version: '1'
    proxy_name: massa-proxy
    k8s-app: eigr-functions-controller
  name: persistentfunctions.functions.eigr.io
spec:
  additionalPrinterColumns: []
  group: functions.eigr.io
  names:
    kind: PersistentFunction
    plural: persistentfunctions
    shortNames:
      - pf
      - pfs
      - pfc
      - pfcs
      - pfunc
      - pfunction
      - pfuncs
      - pfunctions
      - persistentfunction
      - persistentfunctions
    singular: persistentfunction
  scope: Cluster
  version: v1

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    cloudsate_protocol_major_version: '0'
    cloudsate_protocol_minor_version: '1'
    eigr_functions_protocol_major_version: '0'
    eigr_functions_protocol_minor_version: '1'
    proxy_name: massa-proxy
    k8s-app: eigr-functions-controller
  name: eigr-functions-controller
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - functions.eigr.io
    resources:
      - functions
    verbs:
      - '*'
  - apiGroups:
      - functions.eigr.io
    resources:
      - persistentfunctions
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - '*'
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscaler
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - configmaps
      - horizontalpodautoscaler
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - configmaps
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - statefulsets
      - deployments
    verbs:
      - '*'

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    cloudsate_protocol_major_version: '0'
    cloudsate_protocol_minor_version: '1'
    eigr_functions_protocol_major_version: '0'
    eigr_functions_protocol_minor_version: '1'
    proxy_name: massa-proxy
    k8s-app: eigr-functions-controller
  name: eigr-functions-controller
  namespace: eigr-functions

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    cloudsate_protocol_major_version: '0'
    cloudsate_protocol_minor_version: '1'
    eigr_functions_protocol_major_version: '0'
    eigr_functions_protocol_minor_version: '1'
    proxy_name: massa-proxy
    k8s-app: eigr-functions-controller
  name: eigr-functions-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eigr-functions-controller
subjects:
  - kind: ServiceAccount
    name: eigr-functions-controller
    namespace: eigr-functions
