---
apiVersion: cloudstate.io/v1alpha1
kind: StatefulService
metadata:
  name: shopping-cart
  namespace: default
  replicas: 1
spec:
  containers:
  - image: cloudstateio/cloudstate-python-tck:latest