apiVersion: v1
kind: Service
metadata:
  name: proxy-headless-svc
  namespace: default
spec:
  clusterIP: None
  selector:
    app: proxy
  ports:
    - name: epmd
      port: 4369
    - name: proxy
      port: 9000
    - name: http
      port: 9001
