---
apiVersion: functions.eigr.io/v1
kind: Function
metadata:
  name: simple-function
spec:
  backend:
    image: cloudstateio/cloudstate-python-tck:latest
    expose:
      method: loadbalancer
      loadBalancer:
        port: 8080
        targetPort: 9000